#! /bin/bash -x

source $HOME/.git-manager.rc

if [ $1 != "" ]; then
	test -d $1 || mkdir $1
	cd $1
	touch README.md
	git init 
	url=$WEBSERVICE_URL?n=$1
	curl $url
	git remote add origin $GIT_REPOS_REMOTE_USER@$GIT_REPOS_REMOTE_HOST:$GIT_REPOS_REMOTE_HOME/$1.git
	git add README.md
	echo "README" > README.md
	echo "======" >> README.md
	echo $AUTHOR_STRING >> README.md
	git commit -m "__START__"
	git push origin master
else
	echo "Usage: $0 <project-name>"
fi

