#! /bin/bash -x

#cd $(dirname $0)

GIT_REPOS_REMOTE_HOME="/home2/dbthunde/src.repos"
GIT_REPOS_REMOTE_USER=dbthunde
GIT_REPOS_REMOTE_HOST=dbthunder.com

AUTHOR_STRING="Paolo Lulli 2013 - paolo@lulli.net"
#/home2/dbthunde/repos/allmyvideos/

WEBSERVICE_URL="http://src.dbthunder.com/scm/scm.php"

if [ $1 != "" ]; then
	mkdir $1 && cd $1
	touch README.md
	git init 
	url=$WEBSERVICE_URL?n=$1
	curl $url
	git remote add origin $GIT_REPOS_REMOTE_USER@$GIT_REPOS_REMOTE_HOST:$GIT_REPOS_REMOTE_HOME/$1.git
	git add README.md
	echo "README" > README.md
	echo "======" >> README.md
	echo $AUTHOR_STRING >> README.md
	git commit -m "__START__"
	git push origin master
else
	echo "Usage: $0 <project-name>"
fi

